
services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: hotel_user
      POSTGRES_PASSWORD: hotel_password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U hotel_user -d hotel_db" ]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    command: bash -c "while ! nc -z db 5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env  # Важно! Загружаем переменные из .env файла
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  media_volume: