# Generated by Django 5.1.7 on 2025-06-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_status_alter_booking_check_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='photo',
            field=models.ImageField(default='', upload_to='room_photos/'),
            preserve_default=False,
        ),
    ]
